Booker/config/routes.rb
Rails.application.routes.draw do
	root to: 'books#index'
	get 'books' => 'books#lists', as: 'lists'
	post 'books' => 'books#create'
	get 'books/:id' => 'books#show', as: 'book'
	get 'books/:id/edit' => 'books#edit', as: 'edit'
	patch 'books/:id/' => 'books#update'
	delete 'books/:id' => 'books#destroy', as: 'destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Booker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Booker/app/models/book.rb
class Book < ApplicationRecord
end

Booker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Booker/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def lists
  	@books = Book.all
  	@book = Book.new
  end

  def create
  	book = Book.new(book_params)
	if book.save
		flash[:notice] = 'Book was successfully created.'
		redirect_to book_path(book)
  	end
  end

  def show
  	@book = Book.find(params[:id])
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	book = Book.find(params[:id])
  	if book.update(book_params)
		flash[:notice] = 'Book was successfully updated.'
		redirect_to book_path(book)
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to lists_path()
  end

  private
  	def book_params
	params.require(:book).permit(:title, :body)
  	end

end

Booker/app/helpers/application_helper.rb
module ApplicationHelper
end

Booker/app/helpers/books_helper.rb
module BooksHelper
end

Booker/app/views/books/edit.html.erb
<h3>Editing Book</h3>

<%= form_for(@book) do |f| %>
	<h5> Title</h5>
	<%= f.text_field :title, class: "book_title" %>
	<h5> Body</h5>
	<%= f.text_field :body, class: "book_body" %>
	<br>
	<%= f.submit 'Update Book' %>
<% end %>

<p><%= link_to "Show", book_path(@book), class: "show_#{@book.id}" %> | <%= link_to "Back", lists_path(), class: "back" %></p>

Booker/app/views/books/index.html.erb
<h2>ようこそ Bookers へ！</h2>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<%= link_to "start", lists_path() %>

Booker/app/views/books/lists.html.erb
<h3> Books</h3>

<table>
	<thead>
		<tr>
			<th> title</th>
			<th> Body</th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td> <%= book.title %></td>
			<td> <%= book.body %></td>
			<td> <%= link_to "Show", book_path(book), class: "show_#{book.id}" %></td>
			<td> <%= link_to "Edit", edit_path(book), class: "edit_#{book.id}" %></td>
			<td> <%= link_to "Destroy", destroy_path(book), method: :delete, class: "destroy_#{book.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<h4> New Book</h4>

<%= form_for(@book) do |f| %>
	<h4> Title</h4>
	<%= f.text_area :title, class: "book_title" %>

	<h4> Body</h4>
	<%= f.text_area :body, class: "book_body" %>

	<%= f.submit 'Create Book' %>
<% end %>

Booker/app/views/books/show.html.erb
<% if flash[:notice] %>
	<p><%=  flash[:notice] %></p>
<% end %>

<h5>Title: <%= @book.title %></h5>

<h5>Body: <%= @book.body %></h5>

<p><%= link_to "Edit" , edit_path(), class: "edit_#{@book.id}" %> | <%= link_to "Back", lists_path(), class: "back" %></p>

Booker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>